services:
  web:
    build:
       dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/testorder
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  nginx:
    build:
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "4200:4200"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
